const KEY="gelirGiderV4", SETTINGS_KEY="gelirGiderSettingsV1", CAT_KEY="gelirGiderCategoriesV1";
let items=[],settings={cards:[{name:"Kart 1",limit:0},{name:"Kart 2",limit:0},{name:"Kart 3",limit:0}]},categories=["Genel","Market","Fatura","Kira","Yakıt","Yemek","Giyim","Sağlık","Diğer"];
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:2}).format(n);
function load(){try{let a=localStorage.getItem(KEY);items=a?JSON.parse(a):[];if(!Array.isArray(items))items=[];let s=localStorage.getItem(SETTINGS_KEY);if(s){let q=JSON.parse(s);if(q?.cards?.length===3)settings=q}let c=localStorage.getItem(CAT_KEY);if(c){let q=JSON.parse(c);if(Array.isArray(q)&&q.length)categories=q}}catch{}}
function save(){localStorage.setItem(KEY,JSON.stringify(items));render()}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function cardExpense(x){return x.type==="Gider"&&x.payment==="Kredi Kartı"&&x.card?.startsWith("c")}
function installmentCount(x){return Math.max(1,Number(x.installments)||1)}
function installmentAmount(x){return x.amount/installmentCount(x)}
function addMonths(ym,n){let [y,m]=ym.split("-").map(Number);m+=n; y+=Math.floor((m-1)/12);m=(m-1)%12+1;return `${y}-${String(m).padStart(2,"0")}`}
function ym(date){return date.slice(0,7)}
function installmentForMonth(x,target){if(!cardExpense(x))return 0;let start=ym(x.date),n=installmentCount(x),diff=(Number(target.slice(0,4))-Number(start.slice(0,4)))*12+Number(target.slice(5))-Number(start.slice(5));return diff>=0&&diff<n?installmentAmount(x):0}
function syncControls(){let old=$("card").value;$("card").innerHTML='<option value="">Kart seç</option>'+settings.cards.map((c,i)=>`<option value="c${i}">${esc(c.name)}</option>`).join("");if([...$("card").options].some(o=>o.value===old))$("card").value=old;$("category").innerHTML=categories.map(c=>`<option>${esc(c)}</option>`).join("")}
function syncPayment(){let g=$("type").value==="Gider",cc=g&&$("payment").value==="Kredi Kartı";$("payment").disabled=!g;$("card").disabled=!cc;$("installmentBox").hidden=!cc;if(!cc){$("card").value="";$("installment").checked=false;$("installmentFields").hidden=true}}
function updateInstallmentPreview(){let active=$("installment").checked,n=Number($("installmentCount").value),amount=Number($("amount").value)||0;$("installmentFields").hidden=!active;if(active&&amount>0)$("installmentPreview").textContent=`Aylık taksit: ${money(amount/n)} · Toplam: ${money(amount)}`;else $("installmentPreview").textContent=""}
function totals(r){return{income:r.filter(x=>x.type==="Gelir").reduce((s,x)=>s+x.amount,0),expense:r.filter(x=>x.type==="Gider").reduce((s,x)=>s+x.amount,0),transfer:r.filter(x=>x.type==="Kasa Transferi").reduce((s,x)=>s+x.amount,0)}}
function render(){
let t=totals(items);$("totalIncome").textContent=money(t.income);$("totalExpense").textContent=money(t.expense);$("net").textContent=money(t.income-t.expense-t.transfer);$("totalTransfer").textContent=money(t.transfer);
let current=new Date().toISOString().slice(0,7);
$("cardSummary").innerHTML=settings.cards.map((c,i)=>{let purchases=items.filter(x=>cardExpense(x)&&x.card==="c"+i).reduce((s,x)=>s+x.amount,0),thisMonth=items.reduce((s,x)=>s+installmentForMonth(x,current)*(x.card==="c"+i),0),future=items.filter(x=>cardExpense(x)&&x.card==="c"+i).reduce((s,x)=>{let start=ym(x.date),n=installmentCount(x),diff=(Number(current.slice(0,4))-Number(start.slice(0,4)))*12+Number(current.slice(5))-Number(start.slice(5));let used=Math.max(0,Math.min(n,diff+1));return s+Math.max(0,n-used)*installmentAmount(x)},0);return `<div><span>${esc(c.name)}</span><strong>${money(purchases)}</strong><small>Bu ay: ${money(thisMonth)} · Gelecek: ${money(future)}</small><small>Limit: ${money(Number(c.limit)||0)}</small></div>`}).join("");
$("mh1").textContent=settings.cards[0].name;$("mh2").textContent=settings.cards[1].name;$("mh3").textContent=settings.cards[2].name;
let months=[...new Set(items.map(x=>x.date.slice(0,7)))];for(let i=1;i<=36;i++)months.push(addMonths(current,i));months=[...new Set(months)].sort().reverse();
$("cardMonthlyList").innerHTML=months.slice(0,36).map(m=>{let v=settings.cards.map((c,i)=>items.reduce((s,x)=>s+installmentForMonth(x,m)*(x.card==="c"+i),0));let label=new Date(m+"-01T00:00:00").toLocaleDateString("tr-TR",{month:"long",year:"numeric"});return `<tr><td>${label}</td><td>${money(v[0])}</td><td>${money(v[1])}</td><td>${money(v[2])}</td><td class="month-card-total">${money(v.reduce((a,b)=>a+b,0))}</td></tr>`}).join("");
$("cardMonthlyEmpty").style.display=items.some(cardExpense)?"none":"block";
let upcoming=[];for(let i=0;i<6;i++){let m=addMonths(current,i);items.filter(cardExpense).forEach(x=>{let due=installmentForMonth(x,m);if(due>0){let start=ym(x.date),idx=(Number(m.slice(0,4))-Number(start.slice(0,4)))*12+Number(m.slice(5))-Number(start.slice(5))+1;upcoming.push({m,card:settings.cards[Number(x.card.slice(1))]?.name||"-",desc:x.description,idx,n:installmentCount(x),amount:due})}})}
$("upcomingList").innerHTML=upcoming.map(x=>`<tr><td>${new Date(x.m+"-01T00:00:00").toLocaleDateString("tr-TR",{month:"long",year:"numeric"})}</td><td>${esc(x.card)}</td><td>${esc(x.desc)}</td><td>${x.idx}/${x.n} · ${money(x.amount)}</td></tr>`).join("");$("upcomingEmpty").style.display=upcoming.length?"none":"block";
let old=$("monthFilter").value;let allMonths=[...new Set(items.map(x=>x.date.slice(0,7)))].sort().reverse();$("monthFilter").innerHTML='<option value="all">Tüm Aylar</option>'+allMonths.map(m=>`<option value="${m}">${new Date(m+"-01T00:00:00").toLocaleDateString("tr-TR",{month:"long",year:"numeric"})}</option>`).join("");$("monthFilter").value=allMonths.includes(old)?old:"all";
let selected=$("monthFilter").value,filtered=selected==="all"?items:items.filter(x=>x.date.startsWith(selected));let mt=totals(filtered);
if(selected!=="all"){mt.expense=items.filter(x=>x.type==="Gider"&&!cardExpense(x)).filter(x=>x.date.startsWith(selected)).reduce((s,x)=>s+x.amount,0)+items.reduce((s,x)=>s+installmentForMonth(x,selected),0)}
$("monthIncome").textContent=money(mt.income);$("monthExpense").textContent=money(mt.expense);$("monthNet").textContent=money(mt.income-mt.expense-mt.transfer);$("monthTransfer").textContent=money(mt.transfer);
let sorted=filtered.slice().sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id);$("list").innerHTML=sorted.map(x=>`<tr class="${x.type==="Gelir"?"income":x.type==="Gider"?"expense":"transfer"}"><td><input class="sel" type="checkbox" data-id="${x.id}"></td><td>${new Date(x.date+"T00:00:00").toLocaleDateString("tr-TR")}</td><td>${esc(x.description)}</td><td>${esc(x.category||"Genel")}</td><td>${x.type}</td><td>${x.type==="Gider"?esc(x.payment||"Nakit"):"-"}</td><td>${cardExpense(x)?esc(settings.cards[Number(x.card.slice(1))]?.name||"-"):"-"}</td><td>${cardExpense(x)?(installmentCount(x)>1?`${installmentCount(x)} taksit`:"Tek çekim"):"-"}</td><td class="amount">${money(cardExpense(x)?installmentAmount(x):x.amount)}${cardExpense(x)&&installmentCount(x)>1?`<small class="total-note"> toplam ${money(x.amount)}</small>`:""}</td></tr>`).join("");$("empty").style.display=sorted.length?"none":"block";
}
$("date").value=new Date().toISOString().slice(0,10);
$("type").addEventListener("change",syncPayment);$("payment").addEventListener("change",syncPayment);$("installment").addEventListener("change",updateInstallmentPreview);$("installmentCount").addEventListener("change",updateInstallmentPreview);$("amount").addEventListener("input",updateInstallmentPreview);$("monthFilter").addEventListener("change",render);
$("form").addEventListener("submit",e=>{e.preventDefault();let type=$("type").value,desc=$("description").value.trim(),amount=Number($("amount").value);if(!desc)return alert("Açıklama gir.");if(!amount||amount<=0)return alert("Geçerli bir tutar gir.");let payment=type==="Gider"?$("payment").value:"",card=payment==="Kredi Kartı"?$("card").value:"",inst=payment==="Kredi Kartı"&&$("installment").checked?Number($("installmentCount").value):1;if(type==="Gider"&&payment==="Kredi Kartı"&&!card)return alert("Kart seç.");items.push({id:Date.now(),date:$("date").value,description:desc,type,payment,card,category:type==="Gider"?$("category").value:"Genel",amount,installments:inst});$("description").value="";$("amount").value="";$("installment").checked=false;updateInstallmentPreview();save()});
$("clearBtn").addEventListener("click",()=>{let ids=[...document.querySelectorAll(".sel:checked")].map(x=>Number(x.dataset.id));if(!ids.length)return alert("Silmek için işlem seç.");if(confirm("Seçili işlemler silinsin mi?")){items=items.filter(x=>!ids.includes(x.id));save()}});
$("clearAllBtn").addEventListener("click",()=>{if(!items.length)return alert("Silinecek kayıt yok.");if(confirm("Tüm işlemler silinecek. Devam edilsin mi?")){items=[];localStorage.removeItem(KEY);render()}});
$("exportBtn").addEventListener("click",()=>{let blob=new Blob([JSON.stringify({settings,categories,items},null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="gelir-gider-yedek.json";a.click();URL.revokeObjectURL(u)});
load();syncControls();syncPayment();render();