const KEY="gelirGiderV4",SET="gelirGiderSettingsV1";let items=[],settings={cards:[{name:"Kart 1",limit:0},{name:"Kart 2",limit:0},{name:"Kart 3",limit:0}]};
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY"}).format(n);
function load(){try{items=JSON.parse(localStorage.getItem(KEY)||"[]");settings=JSON.parse(localStorage.getItem(SET)||JSON.stringify(settings))}catch{}if(!Array.isArray(items))items=[]}
function card(x){return x.type==="Gider"&&x.payment==="Kredi Kartı"&&x.card?.startsWith("c")}function n(x){return Math.max(1,Number(x.installments)||1)}function ym(d){return d.slice(0,7)}
function due(x,m){if(!card(x))return 0;let s=ym(x.date),d=(+m.slice(0,4)-+s.slice(0,4))*12+(+m.slice(5)-+s.slice(5));return d>=0&&d<n(x)?x.amount/n(x):0}
function save(){localStorage.setItem(KEY,JSON.stringify(items));render()}
function render(){let inc=items.filter(x=>x.type==="Gelir").reduce((s,x)=>s+x.amount,0),exp=items.filter(x=>x.type==="Gider").reduce((s,x)=>s+x.amount,0),tr=items.filter(x=>x.type==="Kasa Transferi").reduce((s,x)=>s+x.amount,0);$("totalIncome").textContent=money(inc);$("totalExpense").textContent=money(exp);$("net").textContent=money(inc-exp-tr);$("totalTransfer").textContent=money(tr);
let m=new Date().toISOString().slice(0,7);$("cardSummary").innerHTML=settings.cards.map((c,i)=>{let total=items.filter(x=>card(x)&&x.card==="c"+i).reduce((s,x)=>s+x.amount,0),month=items.reduce((s,x)=>s+due(x,m)*(x.card==="c"+i),0);return `<div><span>${c.name}</span><strong>${money(total)}</strong><small>Bu ay: ${money(month)}</small><small>Limit: ${money(c.limit||0)}</small></div>`}).join("");
let old=$("monthFilter").value,ms=[...new Set(items.map(x=>x.date.slice(0,7)))].sort().reverse();$("monthFilter").innerHTML='<option value="all">Tüm Aylar</option>'+ms.map(x=>`<option value="${x}">${new Date(x+"-01T00:00:00").toLocaleDateString("tr-TR",{month:"long",year:"numeric"})}</option>`).join("");$("monthFilter").value=ms.includes(old)?old:"all";let sel=$("monthFilter").value,r=sel==="all"?items:items.filter(x=>x.date.startsWith(sel)),mi=r.filter(x=>x.type==="Gelir").reduce((s,x)=>s+x.amount,0),me=sel==="all"?exp:items.filter(x=>x.type==="Gider"&&!card(x)&&x.date.startsWith(sel)).reduce((s,x)=>s+x.amount,0)+items.reduce((s,x)=>s+due(x,sel),0),mt=r.filter(x=>x.type==="Kasa Transferi").reduce((s,x)=>s+x.amount,0);$("monthIncome").textContent=money(mi);$("monthExpense").textContent=money(me);$("monthNet").textContent=money(mi-me-mt);$("monthTransfer").textContent=money(mt);
$("list").innerHTML=r.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<tr class="${x.type==="Gelir"?"income":x.type==="Gider"?"expense":"transfer"}"><td><input class="sel" type="checkbox" data-id="${x.id}"></td><td>${new Date(x.date+"T00:00:00").toLocaleDateString("tr-TR")}</td><td>${String(x.description).replace(/[&<>"']/g,"")}</td><td>${x.category||"Genel"}</td><td>${x.type}</td><td>${x.payment||"-"}</td><td>${card(x)?settings.cards[+x.card.slice(1)].name:"-"}</td><td>${card(x)?(n(x)>1?n(x)+" taksit":"Tek çekim"):"-"}</td><td class="amount">${money(card(x)?x.amount/n(x):x.amount)}</td></tr>`).join("");$("empty").style.display=$("list").innerHTML?"none":"block"}
$("date").value=new Date().toISOString().slice(0,10);$("card").innerHTML='<option value="">Kart seç</option>'+settings.cards.map((c,i)=>`<option value="c${i}">${c.name}</option>`).join("");
function sync(){let g=$("type").value==="Gider",c=g&&$("payment").value==="Kredi Kartı";$("payment").disabled=!g;$("card").disabled=!c;$("installmentBox").hidden=!c}$("type").onchange=sync;$("payment").onchange=sync;
$("form").onsubmit=e=>{e.preventDefault();let t=$("type").value,a=Number($("amount").value),p=t==="Gider"?$("payment").value:"",c=p==="Kredi Kartı"?$("card").value:"";if(!a)return alert("Geçerli tutar gir.");if(p==="Kredi Kartı"&&!c)return alert("Kart seç.");items.push({id:Date.now(),date:$("date").value,description:$("description").value.trim(),type:t,payment:p,card:c,category:t==="Gider"?$("category").value:"Genel",amount:a,installments:p==="Kredi Kartı"&&$("installment").checked?Number($("installmentCount").value):1});$("description").value="";$("amount").value="";save()};
$("monthFilter").onchange=render;$("clearBtn").onclick=()=>{let ids=[...document.querySelectorAll(".sel:checked")].map(x=>+x.dataset.id);items=items.filter(x=>!ids.includes(x.id));save()};$("clearAllBtn").onclick=()=>{if(confirm("Tüm kayıtlar silinsin mi?")){items=[];save()}};$("exportBtn").onclick=()=>{let a=document.createElement("a"),u=URL.createObjectURL(new Blob([JSON.stringify(items,null,2)],{type:"application/json"}));a.href=u;a.download="gelir-gider-yedek.json";a.click()};load();sync();render();